const ROLES = { USER: 'USER', ADMIN: 'ADMIN' };

const VEHICLE_TYPES = ['MOTORCYCLE', 'CAR', 'COMMERCIAL'];

const SESSION_STATUS = { ACTIVE: 'ACTIVE', COMPLETED: 'COMPLETED', EMERGENCY: 'EMERGENCY' };

const SENSOR_STATUS = { ONLINE: 'ONLINE', OFFLINE: 'OFFLINE', WARNING: 'WARNING', ERROR: 'ERROR' };

const SENSOR_TYPES = [
  'GPS',
  'CAMERA',
  'ACCELEROMETER',
  'GYROSCOPE',
  'HELMET',
  'SEATBELT',
  'ALCOHOL',
  'EYE',
  'RAIN',
  'ULTRASONIC',
];

const EMERGENCY_TRIGGER_TYPES = {
  MANUAL_SOS: 'MANUAL_SOS',
  CRASH_DETECTED: 'CRASH_DETECTED',
  HARSH_IMPACT: 'HARSH_IMPACT',
  DROWSINESS_CRITICAL: 'DROWSINESS_CRITICAL',
};

const EMERGENCY_STATUS = { TRIGGERED: 'TRIGGERED', CONTACTED: 'CONTACTED', RESOLVED: 'RESOLVED' };

const SEVERITY = { INFO: 'INFO', WARNING: 'WARNING', CRITICAL: 'CRITICAL' };

const INITIAL_SAFETY_SCORE = 85;
const INITIAL_POINTS = 100;
const MAX_SAFETY_SCORE = 100;
const MIN_SAFETY_SCORE = 0;

const SAFE_BEHAVIOUR_POINTS = {
  HELMET: 10,
  SEAT_BELT: 10,
  SPEED_LIMIT: 15,
  NO_MOBILE_USAGE: 20,
  SMOOTH_DRIVING: 20,
  SAFE_BRAKING: 15,
  TRAFFIC_SIGNALS: 15,
  DRIVE_10_KM: 25,
  DAILY_CHALLENGE: 50,
  WEEKLY_SAFE_DRIVER: 100,
};

const SAFE_BEHAVIOUR_SCORE = {
  HELMET: 2,
  SEAT_BELT: 2,
  SPEED_LIMIT: 3,
  NO_MOBILE_USAGE: 4,
  SMOOTH_DRIVING: 4,
  SAFE_BRAKING: 3,
  TRAFFIC_SIGNALS: 3,
  DRIVE_10_KM: 5,
  DAILY_CHALLENGE: 10,
  WEEKLY_SAFE_DRIVER: 15,
};

const VIOLATION_POINTS = {
  NO_HELMET: 50,
  NO_SEATBELT: 50,
  PHONE_USAGE: 100,
  OVERSPEED: 100,
  WRONG_SIDE: 150,
  SIGNAL_JUMP: 200,
  RASH_DRIVING: 150,
  DRINK_DRIVING: 500,
  DROWSINESS: 100,
};

const VIOLATION_SCORE_PENALTY = {
  NO_HELMET: 8,
  NO_SEATBELT: 8,
  PHONE_USAGE: 12,
  OVERSPEED: 10,
  WRONG_SIDE: 15,
  SIGNAL_JUMP: 18,
  RASH_DRIVING: 15,
  DRINK_DRIVING: 40,
  DROWSINESS: 12,
};

const VIOLATION_SEVERITY = {
  NO_HELMET: 'CRITICAL',
  NO_SEATBELT: 'CRITICAL',
  PHONE_USAGE: 'CRITICAL',
  OVERSPEED: 'WARNING',
  WRONG_SIDE: 'CRITICAL',
  SIGNAL_JUMP: 'CRITICAL',
  RASH_DRIVING: 'CRITICAL',
  DRINK_DRIVING: 'CRITICAL',
  DROWSINESS: 'WARNING',
};

const DEFAULT_SPEED_LIMIT = 60;

const LOCATIONS = {
  BHAVNAGAR: { latitude: 21.7645, longitude: 72.1519, address: 'Bhavnagar, Gujarat' },
  GEC_BHAVNAGAR: { latitude: 21.7729, longitude: 72.1519, address: 'GEC Bhavnagar, Gujarat' },
  AHMEDABAD: { latitude: 23.0225, longitude: 72.5714, address: 'Ahmedabad, Gujarat' },
};

module.exports = {
  ROLES,
  VEHICLE_TYPES,
  SESSION_STATUS,
  SENSOR_STATUS,
  SENSOR_TYPES,
  EMERGENCY_TRIGGER_TYPES,
  EMERGENCY_STATUS,
  SEVERITY,
  INITIAL_SAFETY_SCORE,
  INITIAL_POINTS,
  MAX_SAFETY_SCORE,
  MIN_SAFETY_SCORE,
  SAFE_BEHAVIOUR_POINTS,
  SAFE_BEHAVIOUR_SCORE,
  VIOLATION_POINTS,
  VIOLATION_SCORE_PENALTY,
  VIOLATION_SEVERITY,
  DEFAULT_SPEED_LIMIT,
  LOCATIONS,
};
